export default [
  {
    id: "FLIGHT001ABC",
    airline: "Delta Airlines",
    airline_logo: "https://example.com/delta_logo.png",
    start_location: "New York",
    start_airport: "JFK",
    destination: "Los Angeles",
    destination_airport: "LAX",
    start_time: "2024-05-10T08:00:00",
    duration: "05:30",
    mode: "non-stop",
    type: "one-way",
    class: "economy",
    date: "2024-05-10",
    price: 950,
  },
  {
    id: "FLIGHT002DEF",
    airline: "United Airlines",
    airline_logo: "https://example.com/united_logo.png",
    start_location: "Chicago",
    start_airport: "ORD",
    destination: "Miami",
    destination_airport: "MIA",
    start_time: "2024-05-12T12:30:00",
    duration: "03:45",
    mode: "one-stop",
    type: "round-trip",
    class: "business",
    date: "2024-05-12",
    price: 1800,
  },
  {
    id: "FLIGHT003GHI",
    airline: "American Airlines",
    airline_logo: "https://example.com/american_logo.png",
    start_location: "Dallas",
    start_airport: "DFW",
    destination: "Seattle",
    destination_airport: "SEA",
    start_time: "2024-05-14T10:45:00",
    duration: "06:15",
    mode: "non-stop",
    type: "multi-city",
    class: "first class",
    date: "2024-05-14",
    price: 3500,
  },
  {
    id: "FLIGHT004JKL",
    airline: "Delta Airlines",
    airline_logo: "https://example.com/delta_logo.png",
    start_location: "Los Angeles",
    start_airport: "LAX",
    destination: "New York",
    destination_airport: "JFK",
    start_time: "2024-05-15T11:30:00",
    duration: "05:45",
    mode: "non-stop",
    type: "one-way",
    class: "business",
    date: "2024-05-15",
    price: 2200,
  },
  {
    id: "FLIGHT005MNO",
    airline: "United Airlines",
    airline_logo: "https://example.com/united_logo.png",
    start_location: "Miami",
    start_airport: "MIA",
    destination: "Chicago",
    destination_airport: "ORD",
    start_time: "2024-05-17T14:15:00",
    duration: "03:30",
    mode: "non-stop",
    type: "round-trip",
    class: "economy",
    date: "2024-05-17",
    price: 1200,
  },
  {
    id: "FLIGHT006PQR",
    airline: "American Airlines",
    airline_logo: "https://example.com/american_logo.png",
    start_location: "Seattle",
    start_airport: "SEA",
    destination: "Dallas",
    destination_airport: "DFW",
    start_time: "2024-05-19T09:00:00",
    duration: "06:30",
    mode: "one-stop",
    type: "multi-city",
    class: "first class",
    date: "2024-05-19",
    price: 2800,
  },
  {
    id: "FLIGHT007STU",
    airline: "Delta Airlines",
    airline_logo: "https://example.com/delta_logo.png",
    start_location: "New York",
    start_airport: "JFK",
    destination: "San Francisco",
    destination_airport: "SFO",
    start_time: "2024-05-21T08:45:00",
    duration: "06:00",
    mode: "non-stop",
    type: "one-way",
    class: "economy",
    date: "2024-05-21",
    price: 1100,
  },
  {
    id: "FLIGHT008VWX",
    airline: "United Airlines",
    airline_logo: "https://example.com/united_logo.png",
    start_location: "Chicago",
    start_airport: "ORD",
    destination: "Denver",
    destination_airport: "DEN",
    start_time: "2024-05-23T13:00:00",
    duration: "02:15",
    mode: "non-stop",
    type: "round-trip",
    class: "business",
    date: "2024-05-23",
    price: 1500,
  },
  {
    id: "FLIGHT009YZA",
    airline: "American Airlines",
    airline_logo: "https://example.com/american_logo.png",
    start_location: "Dallas",
    start_airport: "DFW",
    destination: "Miami",
    destination_airport: "MIA",
    start_time: "2024-05-25T10:30:00",
    duration: "04:45",
    mode: "one-stop",
    type: "multi-city",
    class: "first class",
    date: "2024-05-25",
    price: 2300,
  },
  {
    id: "FLIGHT010BCD",
    airline: "Delta Airlines",
    airline_logo: "https://example.com/delta_logo.png",
    start_location: "Los Angeles",
    start_airport: "LAX",
    destination: "Chicago",
    destination_airport: "ORD",
    start_time: "2024-05-27T12:20:00",
    duration: "04:30",
    mode: "one-stop",
    type: "one-way",
    class: "economy",
    date: "2024-05-27",
    price: 1400,
  },
  {
    id: "FLIGHT011DEF",
    airline: "United Airlines",
    airline_logo: "https://example.com/united_logo.png",
    start_location: "Miami",
    start_airport: "MIA",
    destination: "Seattle",
    destination_airport: "SEA",
    start_time: "2024-05-29T09:45:00",
    duration: "06:45",
    mode: "non-stop",
    type: "round-trip",
    class: "business",
    date: "2024-05-29",
    price: 2500,
  },
  {
    id: "FLIGHT012EFG",
    airline: "American Airlines",
    airline_logo: "https://example.com/american_logo.png",
    start_location: "Seattle",
    start_airport: "SEA",
    destination: "New York",
    destination_airport: "JFK",
    start_time: "2024-05-31T11:00:00",
    duration: "05:15",
    mode: "non-stop",
    type: "multi-city",
    class: "first class",
    date: "2024-05-31",
    price: 3200,
  },
  {
    id: "FLIGHT013GHI",
    airline: "Delta Airlines",
    airline_logo: "https://example.com/delta_logo.png",
    start_location: "New York",
    start_airport: "JFK",
    destination: "London",
    destination_airport: "LHR",
    start_time: "2024-06-02T14:00:00",
    duration: "07:30",
    mode: "non-stop",
    type: "one-way",
    class: "economy",
    date: "2024-06-02",
    price: 1900,
  },
  {
    id: "FLIGHT014HIJ",
    airline: "United Airlines",
    airline_logo: "https://example.com/united_logo.png",
    start_location: "Chicago",
    start_airport: "ORD",
    destination: "Paris",
    destination_airport: "CDG",
    start_time: "2024-06-04T16:20:00",
    duration: "08:15",
    mode: "one-stop",
    type: "round-trip",
    class: "business",
    date: "2024-06-04",
    price: 2700,
  },
  {
    id: "FLIGHT015IJK",
    airline: "American Airlines",
    airline_logo: "https://example.com/american_logo.png",
    start_location: "Dallas",
    start_airport: "DFW",
    destination: "Tokyo",
    destination_airport: "HND",
    start_time: "2024-06-06T18:30:00",
    duration: "11:00",
    mode: "non-stop",
    type: "multi-city",
    class: "first class",
    date: "2024-06-06",
    price: 4200,
  },
  {
    id: "FLIGHT016JKL",
    airline: "Delta Airlines",
    airline_logo: "https://example.com/delta_logo.png",
    start_location: "Los Angeles",
    start_airport: "LAX",
    destination: "Sydney",
    destination_airport: "SYD",
    start_time: "2024-06-08T10:45:00",
    duration: "14:00",
    mode: "one-stop",
    type: "one-way",
    class: "economy",
    date: "2024-06-08",
    price: 2800,
  },
  {
    id: "FLIGHT017KLM",
    airline: "United Airlines",
    airline_logo: "https://example.com/united_logo.png",
    start_location: "Miami",
    start_airport: "MIA",
    destination: "Singapore",
    destination_airport: "SIN",
    start_time: "2024-06-10T08:00:00",
    duration: "16:30",
    mode: "non-stop",
    type: "round-trip",
    class: "business",
    date: "2024-06-10",
    price: 4900,
  },
  {
    id: "FLIGHT018LMN",
    airline: "American Airlines",
    airline_logo: "https://example.com/american_logo.png",
    start_location: "Seattle",
    start_airport: "SEA",
    destination: "Dubai",
    destination_airport: "DXB",
    start_time: "2024-06-12T13:15:00",
    duration: "13:45",
    mode: "one-stop",
    type: "multi-city",
    class: "first class",
    date: "2024-06-12",
    price: 4700,
  },
  {
    id: "FLIGHT019MNO",
    airline: "Delta Airlines",
    airline_logo: "https://example.com/delta_logo.png",
    start_location: "New York",
    start_airport: "JFK",
    destination: "Tokyo",
    destination_airport: "HND",
    start_time: "2024-06-14T09:30:00",
    duration: "14:45",
    mode: "one-stop",
    type: "one-way",
    class: "economy",
    date: "2024-06-14",
    price: 3200,
  },
  {
    id: "FLIGHT020NOP",
    airline: "United Airlines",
    airline_logo: "https://example.com/united_logo.png",
    start_location: "Chicago",
    start_airport: "ORD",
    destination: "London",
    destination_airport: "LHR",
    start_time: "2024-06-16T11:00:00",
    duration: "07:30",
    mode: "non-stop",
    type: "round-trip",
    class: "business",
    date: "2024-06-16",
    price: 3500,
  },
];
